theme = "onedark"

[keys.insert]
"C-[" = "normal_mode"

[editor]
line-number = "relative"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
